### ISSUE TITLE
Add birthday notifications

### ISSUE THREAD

**Issue by TheCodeSummoner** [TheCodeSummoner/dof-discord-bot#51]
- [ ] There exists a new birthday cog
- [ ] You can register a new birthday using a command, providing a date and a discord user
- [ ] The above command errors out if date format is wrong
- [ ] The command errors out if the user couldn't be found
- [ ] The command errors out if that user's birthday was already registered
- [ ] You can un-register an existing birthday (in case of errors or someone being kicked out of our discord)
- [ ] The above command errors out if the date format is wrong
- [ ] The command errors out if given birthday + user combination wasn't registered yet
- [ ] Both commands are either admin-only, or register is defender-only and unregister is admin-only
- [ ] Birthdays are stored on disk, in a simple, text-based format
- [ ] Local birthdays are loaded on each run (as date -> user mapping), but are never pushed to the remote repository
- [ ] There exists a listener checking if today is someone's birthday, and sends a notification to chat if so
- [ ] There exists a defender-only command which displays months with days (full calendar with marked birthdays if possible, or just a list of birthdays)
- [ ] The above command uses a custom session
- [ ] The above session has exactly 13 browsable pages (help + months) - subject to discussion, might be better to just have everything sorted alphabetically or by date
- [ ] There exists a command which returns a session with a single month
- [ ] The above command errors out if the month is invalid
- [ ] There exists a command which returns a birthday date given a discord user
- [ ] The above command errors out if the user couldn't be found
- [ ] The command errors out if the requested user is not a Defender - subject to discussion
- [ ] The command sends a notification if this user doesn't have their birthday registered
